services:
  dev-postgres:
    image: postgres:14
    container_name: dev-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs-crud
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge